import { describe, expect, it } from 'vitest';
import * as askrUi from '../src';

describe('Public API', () => {
  it('exposes the 1.0 public component surface from the root entrypoint', () => {
    expect(askrUi.FocusRing).toBeDefined();
    expect(askrUi.FocusScope).toBeDefined();
    expect(askrUi.DismissableLayer).toBeDefined();
    expect(askrUi.Dialog).toBeDefined();
    expect(askrUi.AlertDialog).toBeDefined();
    expect(askrUi.Popover).toBeDefined();
    expect(askrUi.Tooltip).toBeDefined();
    expect(askrUi.Menu).toBeDefined();
    expect(askrUi.DropdownMenu).toBeDefined();
    expect(askrUi.Select).toBeDefined();
    expect(askrUi.Collapsible).toBeDefined();
    expect(askrUi.CollapsibleTrigger).toBeDefined();
    expect(askrUi.CollapsibleContent).toBeDefined();
    expect(askrUi.COLLAPSIBLE_A11Y_CONTRACT).toBeDefined();
    expect(askrUi.Badge).toBeDefined();
    expect(askrUi.Avatar).toBeDefined();
    expect(askrUi.Skeleton).toBeDefined();
    expect(askrUi.Progress).toBeDefined();
    expect(askrUi.ProgressCircle).toBeDefined();
    expect(askrUi.Spinner).toBeDefined();
    expect(askrUi.Breadcrumb).toBeDefined();
    expect(askrUi.Pagination).toBeDefined();
    expect(askrUi.Accordion).toBeDefined();
    expect(askrUi.Tabs).toBeDefined();
    expect(askrUi.ToggleGroup).toBeDefined();
    expect(askrUi.ToastProvider).toBeDefined();
    expect(askrUi.Slider).toBeDefined();
    expect(askrUi.Menubar).toBeDefined();
    expect(askrUi.NavigationMenu).toBeDefined();
    // Layout primitives
    expect(askrUi.Container).toBeDefined();
    expect(askrUi.CONTAINER_A11Y_CONTRACT).toBeDefined();
    expect(askrUi.Stack).toBeDefined();
    expect(askrUi.STACK_A11Y_CONTRACT).toBeDefined();
    expect(askrUi.Inline).toBeDefined();
    expect(askrUi.INLINE_A11Y_CONTRACT).toBeDefined();
    expect(askrUi.Grid).toBeDefined();
    expect(askrUi.GRID_A11Y_CONTRACT).toBeDefined();
    expect(askrUi.Center).toBeDefined();
    expect(askrUi.CENTER_A11Y_CONTRACT).toBeDefined();
    expect(askrUi.Spacer).toBeDefined();
    expect(askrUi.SPACER_A11Y_CONTRACT).toBeDefined();
    expect(askrUi.SidebarLayout).toBeDefined();
    expect(askrUi.SIDEBAR_LAYOUT_A11Y_CONTRACT).toBeDefined();
    expect(askrUi.TopbarLayout).toBeDefined();
    expect(askrUi.TOPBAR_LAYOUT_A11Y_CONTRACT).toBeDefined();
    expect(askrUi.IconBase).toBeDefined();
    expect(askrUi.getIconContractProps).toBeDefined();
    expect(askrUi.resolveIconSizeVariable).toBeDefined();
  });
});
