export const DATA_TABLE_A11Y_CONTRACT = {
  SORT_ATTRIBUTE: 'aria-sort' as const,
  SORT_VALUES: {
    ascending: 'ascending' as const,
    descending: 'descending' as const,
    none: 'none' as const,
  },
  SELECTED_ATTRIBUTE: 'aria-selected' as const,
  CHECKED_ATTRIBUTE: 'aria-checked' as const,
  EXPANDED_ATTRIBUTE: 'aria-expanded' as const,
  CONTROLS_ATTRIBUTE: 'aria-controls' as const,
  BUSY_ATTRIBUTE: 'aria-busy' as const,
  LIVE_REGION: 'aria-live' as const,
  LIVE_POLITE: 'polite' as const,
  KEYBOARD_ACTIVATION: ['Enter', 'Space'] as const,
  DATA_ATTRIBUTES: {
    slot: 'data-slot' as const,
    state: 'data-state' as const,
    disabled: 'data-disabled' as const,
    selected: 'data-selected' as const,
    expanded: 'data-expanded' as const,
    sortDirection: 'data-sort-direction' as const,
    columnId: 'data-column-id' as const,
    rowId: 'data-row-id' as const,
    responsiveMode: 'data-responsive-mode' as const,
    responsiveView: 'data-responsive-view' as const,
  },
  SLOTS: {
    root: 'data-table' as const,
    toolbar: 'data-table-toolbar' as const,
    search: 'data-table-search' as const,
    content: 'data-table-content' as const,
    table: 'data-table-table' as const,
    thead: 'data-table-thead' as const,
    headerRow: 'data-table-header-row' as const,
    head: 'data-table-head' as const,
    tbody: 'data-table-tbody' as const,
    row: 'data-table-row' as const,
    cell: 'data-table-cell' as const,
    expandedRow: 'data-table-expanded-row' as const,
    expandedCell: 'data-table-expanded-cell' as const,
    list: 'data-table-list' as const,
    listItem: 'data-table-list-item' as const,
    listMain: 'data-table-list-main' as const,
    listMeta: 'data-table-list-meta' as const,
    listActions: 'data-table-list-actions' as const,
    listExpanded: 'data-table-list-expanded' as const,
    pagination: 'data-table-pagination' as const,
    empty: 'data-table-empty' as const,
    loading: 'data-table-loading' as const,
    error: 'data-table-error' as const,
  },
} as const;

export type DataTableA11yContract = typeof DATA_TABLE_A11Y_CONTRACT;
