name: Publish Package

on:
  workflow_dispatch:

jobs:
  ci:
    uses: ./.github/workflows/ci.yml
    permissions:
      contents: read

  publish:
    needs: ci
    uses: askrjs/actions/.github/workflows/publish-package.yml@d3c866509a8245456fcd6fd929d5493737beddde
    with:
      install-playwright: true
    permissions:
      contents: write
      id-token: write
      packages: read
